### ISSUE TITLE
Better Heroku integration

### ISSUE THREAD

**Issue by hilsmann** [Staffbase/create-staffbase-plugin-nodejs#27]
Hello,

I have today integrated my Staffbase plugin to Heroku. And find out that there appear an error that the "$PORT" could not be bind.

I figured out that I have to switch from this

`server.listen(port, '127.0.0.1');`

to this

`var host = process.env.YOUR_HOST || '0.0.0.0';
server.listen(port, host);`

In the "www" file.

So my Question is. Could you change those lines, so everyone could instantly deploy there Staffbase Plugin into Heroku without errors? :)

Best regrets

Sven

**Comment by Ninerian** [comment]
Hello Sven,

thanks for your proposal. We will check internally if we have time to implement it. In the meanwhile feel free to open a PR for this change.

**Comment by axdotl** [comment]
Closed, will be archived.
